"""Update multi-library constraints and indexes

Revision ID: 0941cbe6d514
Revises: 47cdbaee7220
Create Date: 2026-10-10 14:14:49.032226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0941cbe6d514'
down_revision = '47cdbaee7220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_transactions_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transactions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_transactions_library_id'), ['library_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('books_book_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_books_library_id'), ['library_id'], unique=False)
        batch_op.create_unique_constraint('uq_books_library_book_code', ['library_id', 'book_code'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('employees_employee_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_employees_library_id'), ['library_id'], unique=False)
        batch_op.create_unique_constraint('uq_employees_library_employee_code', ['library_id', 'employee_code'])

    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_history_library_id'), ['library_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_library_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('transaction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_history_library_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employees_library_employee_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_employees_library_id'))
        batch_op.create_unique_constraint(batch_op.f('employees_employee_code_key'), ['employee_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_books_library_book_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_books_library_id'))
        batch_op.create_unique_constraint(batch_op.f('books_book_code_key'), ['book_code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('book_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_transactions_library_id'))
        batch_op.drop_index(batch_op.f('ix_book_transactions_employee_id'))
        batch_op.drop_index(batch_op.f('ix_book_transactions_book_id'))

    # ### end Alembic commands ###
