"""Create libraries table

Revision ID: 626743133944
Revises: 959596f96917
Create Date: 2026-10-10 10:58:34.616672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626743133944'
down_revision = '959596f96917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libraries')
    # ### end Alembic commands ###
